### ISSUE TITLE
Тезисы на конференцию

### ISSUE THREAD

**Issue by vlasenkoandrew** [LuNA-Static-Analysis/LuNA-Static-Analysis-Repository#30]

**Comment by m-michurov** [comment]
Тезисы: https://docs.google.com/document/d/1YiMqP8lcp4rUtao0Wd5GWw2xnTy1Qmm5ycqa6Q7gE8g/edit?usp=sharing

**Comment by VTsarevNSU** [comment]
тезисы дополнить до 400 слов тем, у кого не хватает; уведомить об этом в вк до воскресенья

**Comment by VTsarevNSU** [comment]
тезисы, возможно, придётся дорабатывать по фидбеку от организаторов
