### ISSUE TITLE
Придумать название для нашей общей утилиты поиска ошибок

### ISSUE THREAD

**Issue by VTsarevNSU** [LuNA-Static-Analysis/LuNA-Static-Analysis-Repository#37]

**Comment by VTsarevNSU** [comment]
моя идея: назвать по тематике трёх мушкетёров и Д'Артаньяна, поскольку у нас 3 анализатора одного типа и 1 другого, плюс они все друг друга кроют дубликатами ошибок

**Comment by VTsarevNSU** [comment]
Я вот о таком подумал: ADAPT
A — Analyzer
D — DDG
A — AST
P — Prolog
T — Trace
Имеет аббревиатурный смысл и при этом является понятным английским словом.

**Comment by vlasenkoandrew** [comment]
Ну пора уже закрывать задачу!
