### ISSUE TITLE
Создать формат для всех ошибок и реализовать автоматические репорты для всех средств отладки

### ISSUE THREAD

**Issue by VTsarevNSU** [LuNA-Static-Analysis/LuNA-Static-Analysis-Repository#6]
1) Разработать формат JSON или YAML или др. - Михаил
2) Реализовать вывод ошибок в данном формате - все

**Comment by VTsarevNSU** [comment]
- формат вывода ошибок надо придумать (json, xml)

**Comment by m-michurov** [comment]
https://docs.google.com/document/d/1MnaZl-YvaDj7QQWTje_oWAdjS5TUPKXq9aR-EyD7PGo/edit?usp=sharing
